### ISSUE TITLE
Running timeseries.REFRESHCLUSTER kills the cluster

### ISSUE THREAD

**Issue by namirsab** [RedisGears/LibMR#26]
Check the original issue in Redis Time series repo: https://github.com/RedisTimeSeries/RedisTimeSeries/issues/1215

I duplicated it just in case it better suites here, as the error doesn't seem to be related to Redis Time Series but more with this library.

**Comment by MeirShpilraien** [comment]
Closing, relevant API was added so modules can provide shards password when initialising libmr.
